app:
  port: 8081
  cache_size: 100

kafka:
  brokers:
    - "kafka:29092"
  topic: "orders"

database:
  host: "db"
  port: 5432
  user: "demo_user"
  password: "demo_password"
  dbname: "orders_db"
  sslmode: "disable"